# Generated by Django 4.2 on 2023-05-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='session_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
