# Generated by Django 4.2 on 2023-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_testresult_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test3',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
